apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: # kpt-merge: flux-system/o5gs-up
  name: o5gs-up
  namespace: flux-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'helm.toolkit.fluxcd.io|HelmRelease|flux-system|o5gs-up'
spec:
  interval: 10m
  targetNamespace: open5gs
  install:
    createNamespace: true
  chart:
    spec:
      chart: o5gs-user-plane
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: o5gs
  releaseName: o5gs-up
  values:
    multus:
      macVlanInterface: ens19
